// Generated by delombok at Thu Feb 13 14:20:21 UTC 2025
package io.github.humbleui.skija.shaper;

import org.jetbrains.annotations.*;

public class BidiRun {
    @ApiStatus.Internal
    public final int _end;
    /**
     * The unicode bidi embedding level (even ltr, odd rtl)
     */
    @ApiStatus.Internal
    public final int _level;

    @SuppressWarnings("all")
    public BidiRun(final int end, final int level) {
        this._end = end;
        this._level = level;
    }

    @SuppressWarnings("all")
    public int getEnd() {
        return this._end;
    }

    /**
     * The unicode bidi embedding level (even ltr, odd rtl)
     */
    @SuppressWarnings("all")
    public int getLevel() {
        return this._level;
    }

    @Override
    @SuppressWarnings("all")
    public boolean equals(final Object o) {
        if (o == this)
            return true;
        if (!(o instanceof BidiRun))
            return false;
        final BidiRun other = (BidiRun) o;
        if (!other.canEqual((Object) this))
            return false;
        if (this.getEnd() != other.getEnd())
            return false;
        if (this.getLevel() != other.getLevel())
            return false;
        return true;
    }

    @SuppressWarnings("all")
    protected boolean canEqual(final Object other) {
        return other instanceof BidiRun;
    }

    @Override
    @SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + this.getEnd();
        result = result * PRIME + this.getLevel();
        return result;
    }

    @Override
    @SuppressWarnings("all")
    public String toString() {
        return "BidiRun(_end=" + this.getEnd() + ", _level=" + this.getLevel() + ")";
    }
}
