// Generated by delombok at Thu Feb 13 14:20:21 UTC 2025
package io.github.humbleui.skija.shaper;

import org.jetbrains.annotations.ApiStatus;

public class LanguageRun {
    @ApiStatus.Internal
    public final int _end;
    /**
     * Should be BCP-47, c locale names may also work.
     */
    @ApiStatus.Internal
    public final String _language;

    @SuppressWarnings("all")
    public LanguageRun(final int end, final String language) {
        this._end = end;
        this._language = language;
    }

    @SuppressWarnings("all")
    public int getEnd() {
        return this._end;
    }

    /**
     * Should be BCP-47, c locale names may also work.
     */
    @SuppressWarnings("all")
    public String getLanguage() {
        return this._language;
    }

    @Override
    @SuppressWarnings("all")
    public boolean equals(final Object o) {
        if (o == this)
            return true;
        if (!(o instanceof LanguageRun))
            return false;
        final LanguageRun other = (LanguageRun) o;
        if (!other.canEqual((Object) this))
            return false;
        if (this.getEnd() != other.getEnd())
            return false;
        final Object this$_language = this.getLanguage();
        final Object other$_language = other.getLanguage();
        if (this$_language == null ? other$_language != null : !this$_language.equals(other$_language))
            return false;
        return true;
    }

    @SuppressWarnings("all")
    protected boolean canEqual(final Object other) {
        return other instanceof LanguageRun;
    }

    @Override
    @SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + this.getEnd();
        final Object $_language = this.getLanguage();
        result = result * PRIME + ($_language == null ? 43 : $_language.hashCode());
        return result;
    }

    @Override
    @SuppressWarnings("all")
    public String toString() {
        return "LanguageRun(_end=" + this.getEnd() + ", _language=" + this.getLanguage() + ")";
    }
}
