// Generated by delombok at Thu Feb 13 14:20:21 UTC 2025
package io.github.humbleui.skija.shaper;

import io.github.humbleui.skija.FourByteTag;
import org.jetbrains.annotations.ApiStatus;

public class ScriptRun {
    @ApiStatus.Internal
    public final int _end;
    @ApiStatus.Internal
    public final int _scriptTag;

    public ScriptRun(int end, String script) {
        this(end, FourByteTag.fromString(script));
    }

    /**
     * Should be iso15924 codes.
     */
    public String getScript() {
        return FourByteTag.toString(_scriptTag);
    }

    @SuppressWarnings("all")
    public ScriptRun(final int end, final int scriptTag) {
        this._end = end;
        this._scriptTag = scriptTag;
    }

    @SuppressWarnings("all")
    public int getEnd() {
        return this._end;
    }

    @SuppressWarnings("all")
    public int getScriptTag() {
        return this._scriptTag;
    }

    @Override
    @SuppressWarnings("all")
    public boolean equals(final Object o) {
        if (o == this)
            return true;
        if (!(o instanceof ScriptRun))
            return false;
        final ScriptRun other = (ScriptRun) o;
        if (!other.canEqual((Object) this))
            return false;
        if (this.getEnd() != other.getEnd())
            return false;
        if (this.getScriptTag() != other.getScriptTag())
            return false;
        return true;
    }

    @SuppressWarnings("all")
    protected boolean canEqual(final Object other) {
        return other instanceof ScriptRun;
    }

    @Override
    @SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + this.getEnd();
        result = result * PRIME + this.getScriptTag();
        return result;
    }

    @Override
    @SuppressWarnings("all")
    public String toString() {
        return "ScriptRun(_end=" + this.getEnd() + ", _scriptTag=" + this.getScriptTag() + ")";
    }
}
