// Generated by delombok at Thu Feb 13 14:20:21 UTC 2025
package io.github.humbleui.skija;

public class ColorMatrix {
    public final float[] _mat;

    public ColorMatrix(float... mat) {
        assert mat.length == 20 : "Expected 20 elements, got " + mat == null ? null : mat.length;
        _mat = mat;
    }

    @SuppressWarnings("all")
    public float[] getMat() {
        return this._mat;
    }

    @Override
    @SuppressWarnings("all")
    public boolean equals(final Object o) {
        if (o == this)
            return true;
        if (!(o instanceof ColorMatrix))
            return false;
        final ColorMatrix other = (ColorMatrix) o;
        if (!other.canEqual((Object) this))
            return false;
        if (!java.util.Arrays.equals(this.getMat(), other.getMat()))
            return false;
        return true;
    }

    @SuppressWarnings("all")
    protected boolean canEqual(final Object other) {
        return other instanceof ColorMatrix;
    }

    @Override
    @SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + java.util.Arrays.hashCode(this.getMat());
        return result;
    }

    @Override
    @SuppressWarnings("all")
    public String toString() {
        return "ColorMatrix(_mat=" + java.util.Arrays.toString(this.getMat()) + ")";
    }
}
