// Generated by delombok at Thu Feb 13 14:20:21 UTC 2025
package io.github.humbleui.skija;

import org.jetbrains.annotations.ApiStatus;

public class EncodeWEBPOptions {
    public static final EncodeWEBPOptions DEFAULT = new EncodeWEBPOptions(EncodeWEBPCompressionMode.LOSSY, 100.0F);
    @ApiStatus.Internal
    public final EncodeWEBPCompressionMode _compressionMode;
    @ApiStatus.Internal
    public final float _quality;

    @ApiStatus.Internal
    public EncodeWEBPOptions(EncodeWEBPCompressionMode compression, float quality) {
        _compressionMode = compression;
        _quality = quality;
    }

    @SuppressWarnings("all")
    public EncodeWEBPCompressionMode getCompressionMode() {
        return this._compressionMode;
    }

    @SuppressWarnings("all")
    public float getQuality() {
        return this._quality;
    }

    @Override
    @SuppressWarnings("all")
    public boolean equals(final Object o) {
        if (o == this)
            return true;
        if (!(o instanceof EncodeWEBPOptions))
            return false;
        final EncodeWEBPOptions other = (EncodeWEBPOptions) o;
        if (!other.canEqual((Object) this))
            return false;
        if (Float.compare(this.getQuality(), other.getQuality()) != 0)
            return false;
        final Object this$_compressionMode = this.getCompressionMode();
        final Object other$_compressionMode = other.getCompressionMode();
        if (this$_compressionMode == null ? other$_compressionMode != null
                : !this$_compressionMode.equals(other$_compressionMode))
            return false;
        return true;
    }

    @SuppressWarnings("all")
    protected boolean canEqual(final Object other) {
        return other instanceof EncodeWEBPOptions;
    }

    @Override
    @SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + Float.floatToIntBits(this.getQuality());
        final Object $_compressionMode = this.getCompressionMode();
        result = result * PRIME + ($_compressionMode == null ? 43 : $_compressionMode.hashCode());
        return result;
    }

    @Override
    @SuppressWarnings("all")
    public String toString() {
        return "EncodeWEBPOptions(_compressionMode=" + this.getCompressionMode() + ", _quality=" + this.getQuality()
                + ")";
    }

    /**
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    public EncodeWEBPOptions withCompressionMode(final EncodeWEBPCompressionMode _compressionMode) {
        return this._compressionMode == _compressionMode ? this
                : new EncodeWEBPOptions(_compressionMode, this._quality);
    }

    /**
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    public EncodeWEBPOptions withQuality(final float _quality) {
        return this._quality == _quality ? this : new EncodeWEBPOptions(this._compressionMode, _quality);
    }
}
