// Generated by delombok at Thu Feb 13 14:20:21 UTC 2025
package io.github.humbleui.skija;

import org.jetbrains.annotations.*;

public class FontStyle {
    public final int _value;
    public static final FontStyle NORMAL = new FontStyle(FontWeight.NORMAL, FontWidth.NORMAL, FontSlant.UPRIGHT);
    public static final FontStyle BOLD = new FontStyle(FontWeight.BOLD, FontWidth.NORMAL, FontSlant.UPRIGHT);
    public static final FontStyle ITALIC = new FontStyle(FontWeight.NORMAL, FontWidth.NORMAL, FontSlant.ITALIC);
    public static final FontStyle BOLD_ITALIC = new FontStyle(FontWeight.BOLD, FontWidth.NORMAL, FontSlant.ITALIC);

    public FontStyle(int weight, int width, FontSlant slant) {
        _value = (weight & 65535) | ((width & 255) << 16) | (slant.ordinal() << 24);
    }

    @ApiStatus.Internal
    public FontStyle(int value) {
        this._value = value;
    }

    public int getWeight() {
        return _value & 65535;
    }

    public FontStyle withWeight(int weight) {
        return new FontStyle(weight, getWidth(), getSlant());
    }

    public int getWidth() {
        return (_value >> 16) & 255;
    }

    public FontStyle withWidth(int width) {
        return new FontStyle(getWeight(), width, getSlant());
    }

    public FontSlant getSlant() {
        return FontSlant._values[(_value >> 24) & 255];
    }

    public FontStyle withSlant(FontSlant slant) {
        return new FontStyle(getWeight(), getWidth(), slant);
    }

    @Override
    public String toString() {
        return "FontStyle(" + "weight=" + getWeight() + ", width=" + getWidth() + ", slant=\'" + getSlant() + ')';
    }

    @Override
    @SuppressWarnings("all")
    public boolean equals(final Object o) {
        if (o == this)
            return true;
        if (!(o instanceof FontStyle))
            return false;
        final FontStyle other = (FontStyle) o;
        if (!other.canEqual((Object) this))
            return false;
        if (this._value != other._value)
            return false;
        return true;
    }

    @SuppressWarnings("all")
    protected boolean canEqual(final Object other) {
        return other instanceof FontStyle;
    }

    @Override
    @SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + this._value;
        return result;
    }
}
