// Generated by delombok at Thu Feb 13 14:20:21 UTC 2025
package io.github.humbleui.skija;

public class FontFamilyName {
    public final String _name;
    public final String _language;

    @SuppressWarnings("all")
    public FontFamilyName(final String name, final String language) {
        this._name = name;
        this._language = language;
    }

    @SuppressWarnings("all")
    public String getName() {
        return this._name;
    }

    @SuppressWarnings("all")
    public String getLanguage() {
        return this._language;
    }

    @Override
    @SuppressWarnings("all")
    public boolean equals(final Object o) {
        if (o == this)
            return true;
        if (!(o instanceof FontFamilyName))
            return false;
        final FontFamilyName other = (FontFamilyName) o;
        if (!other.canEqual((Object) this))
            return false;
        final Object this$_name = this.getName();
        final Object other$_name = other.getName();
        if (this$_name == null ? other$_name != null : !this$_name.equals(other$_name))
            return false;
        final Object this$_language = this.getLanguage();
        final Object other$_language = other.getLanguage();
        if (this$_language == null ? other$_language != null : !this$_language.equals(other$_language))
            return false;
        return true;
    }

    @SuppressWarnings("all")
    protected boolean canEqual(final Object other) {
        return other instanceof FontFamilyName;
    }

    @Override
    @SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final Object $_name = this.getName();
        result = result * PRIME + ($_name == null ? 43 : $_name.hashCode());
        final Object $_language = this.getLanguage();
        result = result * PRIME + ($_language == null ? 43 : $_language.hashCode());
        return result;
    }

    @Override
    @SuppressWarnings("all")
    public String toString() {
        return "FontFamilyName(_name=" + this.getName() + ", _language=" + this.getLanguage() + ")";
    }
}
