// Generated by delombok at Thu Feb 13 14:20:21 UTC 2025
package io.github.humbleui.skija;

import org.jetbrains.annotations.ApiStatus;

public class GradientStyle {
    @ApiStatus.Internal
    public static final int _INTERPOLATE_PREMUL = 1;
    public static GradientStyle DEFAULT = new GradientStyle(FilterTileMode.CLAMP, true, null);
    @ApiStatus.Internal
    public final FilterTileMode _tileMode;
    @ApiStatus.Internal
    public final boolean _premul;
    @ApiStatus.Internal
    public final Matrix33 _localMatrix;

    @ApiStatus.Internal
    public int _getFlags() {
        return 0 | (_premul ? _INTERPOLATE_PREMUL : 0);
    }

    @ApiStatus.Internal
    public float[] _getMatrixArray() {
        return _localMatrix == null ? null : _localMatrix.getMat();
    }

    @SuppressWarnings("all")
    public GradientStyle(final FilterTileMode tileMode, final boolean premul, final Matrix33 localMatrix) {
        this._tileMode = tileMode;
        this._premul = premul;
        this._localMatrix = localMatrix;
    }

    @SuppressWarnings("all")
    public FilterTileMode getTileMode() {
        return this._tileMode;
    }

    @SuppressWarnings("all")
    public boolean isPremul() {
        return this._premul;
    }

    @SuppressWarnings("all")
    public Matrix33 getLocalMatrix() {
        return this._localMatrix;
    }

    @Override
    @SuppressWarnings("all")
    public boolean equals(final Object o) {
        if (o == this)
            return true;
        if (!(o instanceof GradientStyle))
            return false;
        final GradientStyle other = (GradientStyle) o;
        if (!other.canEqual((Object) this))
            return false;
        if (this.isPremul() != other.isPremul())
            return false;
        final Object this$_tileMode = this.getTileMode();
        final Object other$_tileMode = other.getTileMode();
        if (this$_tileMode == null ? other$_tileMode != null : !this$_tileMode.equals(other$_tileMode))
            return false;
        final Object this$_localMatrix = this.getLocalMatrix();
        final Object other$_localMatrix = other.getLocalMatrix();
        if (this$_localMatrix == null ? other$_localMatrix != null : !this$_localMatrix.equals(other$_localMatrix))
            return false;
        return true;
    }

    @SuppressWarnings("all")
    protected boolean canEqual(final Object other) {
        return other instanceof GradientStyle;
    }

    @Override
    @SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + (this.isPremul() ? 79 : 97);
        final Object $_tileMode = this.getTileMode();
        result = result * PRIME + ($_tileMode == null ? 43 : $_tileMode.hashCode());
        final Object $_localMatrix = this.getLocalMatrix();
        result = result * PRIME + ($_localMatrix == null ? 43 : $_localMatrix.hashCode());
        return result;
    }

    @Override
    @SuppressWarnings("all")
    public String toString() {
        return "GradientStyle(_tileMode=" + this.getTileMode() + ", _premul=" + this.isPremul() + ", _localMatrix="
                + this.getLocalMatrix() + ")";
    }

    /**
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    public GradientStyle withTileMode(final FilterTileMode _tileMode) {
        return this._tileMode == _tileMode ? this : new GradientStyle(_tileMode, this._premul, this._localMatrix);
    }

    /**
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    public GradientStyle withPremul(final boolean _premul) {
        return this._premul == _premul ? this : new GradientStyle(this._tileMode, _premul, this._localMatrix);
    }

    /**
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    public GradientStyle withLocalMatrix(final Matrix33 _localMatrix) {
        return this._localMatrix == _localMatrix ? this : new GradientStyle(this._tileMode, this._premul, _localMatrix);
    }
}
