// Generated by delombok at Thu Feb 13 14:20:21 UTC 2025
package io.github.humbleui.skija;

import org.jetbrains.annotations.*;

/**
 * <p>
 * 4x4 matrix used by SkCanvas and other parts of Skia.
 * </p>
 *
 * Skia assumes a right-handed coordinate system:
 * +X goes to the right
 * +Y goes down
 * +Z goes into the screen (away from the viewer)
 */
public class Matrix44 {
    /**
     * Matrix elements are in row-major order.
     */
    @ApiStatus.Internal
    public final float[] _mat;

    /**
     * The constructor parameters are in row-major order.
     */
    public Matrix44(float... mat) {
        assert mat.length == 16 : "Expected 16 elements, got " + mat == null ? null : mat.length;
        _mat = mat;
    }

    public static final Matrix44 IDENTITY = new Matrix44(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1);

    /**
     * <p>
     * When converting from Matrix44 to Matrix33, the third row and
     * column is dropped.
     * </p>
     *
     * <pre>
     * <code>
     * [ a b _ c ]      [ a b c ]
     * [ d e _ f ]  -&gt;  [ d e f ]
     * [ _ _ _ _ ]      [ g h i ]
     * [ g h _ i ]
     * </code>
     * </pre>
     */
    public Matrix33 asMatrix33() {
        return new Matrix33(_mat[0], _mat[1], _mat[3], _mat[4], _mat[5], _mat[7], _mat[12], _mat[13], _mat[15]);
    }

    /**
     * Matrix elements are in row-major order.
     */
    @SuppressWarnings("all")
    public float[] getMat() {
        return this._mat;
    }

    @Override
    @SuppressWarnings("all")
    public boolean equals(final Object o) {
        if (o == this)
            return true;
        if (!(o instanceof Matrix44))
            return false;
        final Matrix44 other = (Matrix44) o;
        if (!other.canEqual((Object) this))
            return false;
        if (!java.util.Arrays.equals(this.getMat(), other.getMat()))
            return false;
        return true;
    }

    @SuppressWarnings("all")
    protected boolean canEqual(final Object other) {
        return other instanceof Matrix44;
    }

    @Override
    @SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + java.util.Arrays.hashCode(this.getMat());
        return result;
    }

    @Override
    @SuppressWarnings("all")
    public String toString() {
        return "Matrix44(_mat=" + java.util.Arrays.toString(this.getMat()) + ")";
    }
}
