// Generated by delombok at Thu Feb 13 14:20:21 UTC 2025
package io.github.humbleui.skija;

import org.jetbrains.annotations.*;

public class SurfaceProps {
    @ApiStatus.Internal
    public final boolean _deviceIndependentFonts;
    @ApiStatus.Internal
    public final PixelGeometry _pixelGeometry;

    @ApiStatus.Internal
    public SurfaceProps(boolean deviceIndependentFonts, int pixelGeometry) {
        this(deviceIndependentFonts, PixelGeometry.values()[pixelGeometry]);
    }

    public SurfaceProps() {
        this(false, PixelGeometry.UNKNOWN);
    }

    public SurfaceProps(PixelGeometry geo) {
        this(false, geo);
    }

    @ApiStatus.Internal
    public int _getFlags() {
        return 0 | (_deviceIndependentFonts ? 1 : 0);
    }

    @ApiStatus.Internal
    public int _getPixelGeometryOrdinal() {
        return _pixelGeometry.ordinal();
    }

    @SuppressWarnings("all")
    public boolean isDeviceIndependentFonts() {
        return this._deviceIndependentFonts;
    }

    @SuppressWarnings("all")
    public PixelGeometry getPixelGeometry() {
        return this._pixelGeometry;
    }

    @Override
    @SuppressWarnings("all")
    public boolean equals(final Object o) {
        if (o == this)
            return true;
        if (!(o instanceof SurfaceProps))
            return false;
        final SurfaceProps other = (SurfaceProps) o;
        if (!other.canEqual((Object) this))
            return false;
        if (this.isDeviceIndependentFonts() != other.isDeviceIndependentFonts())
            return false;
        final Object this$_pixelGeometry = this.getPixelGeometry();
        final Object other$_pixelGeometry = other.getPixelGeometry();
        if (this$_pixelGeometry == null ? other$_pixelGeometry != null
                : !this$_pixelGeometry.equals(other$_pixelGeometry))
            return false;
        return true;
    }

    @SuppressWarnings("all")
    protected boolean canEqual(final Object other) {
        return other instanceof SurfaceProps;
    }

    @Override
    @SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + (this.isDeviceIndependentFonts() ? 79 : 97);
        final Object $_pixelGeometry = this.getPixelGeometry();
        result = result * PRIME + ($_pixelGeometry == null ? 43 : $_pixelGeometry.hashCode());
        return result;
    }

    @Override
    @SuppressWarnings("all")
    public String toString() {
        return "SurfaceProps(_deviceIndependentFonts=" + this.isDeviceIndependentFonts() + ", _pixelGeometry="
                + this.getPixelGeometry() + ")";
    }

    /**
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    public SurfaceProps withDeviceIndependentFonts(final boolean _deviceIndependentFonts) {
        return this._deviceIndependentFonts == _deviceIndependentFonts ? this
                : new SurfaceProps(_deviceIndependentFonts, this._pixelGeometry);
    }

    /**
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    public SurfaceProps withPixelGeometry(final PixelGeometry _pixelGeometry) {
        return this._pixelGeometry == _pixelGeometry ? this
                : new SurfaceProps(this._deviceIndependentFonts, _pixelGeometry);
    }

    @SuppressWarnings("all")
    public SurfaceProps(final boolean deviceIndependentFonts, final PixelGeometry pixelGeometry) {
        this._deviceIndependentFonts = deviceIndependentFonts;
        this._pixelGeometry = pixelGeometry;
    }
}
