// Generated by delombok at Thu Feb 13 14:20:21 UTC 2025
package io.github.humbleui.skija.svg;

import org.jetbrains.annotations.*;

public class SVGLength {
    @ApiStatus.Internal
    public final float _value;
    @ApiStatus.Internal
    public final SVGLengthUnit _unit;

    @ApiStatus.Internal
    public SVGLength(float value, int unit) {
        this(value, SVGLengthUnit._values[unit]);
    }

    public SVGLength(float value) {
        this(value, SVGLengthUnit.NUMBER);
    }

    @SuppressWarnings("all")
    public SVGLength(final float value, final SVGLengthUnit unit) {
        this._value = value;
        this._unit = unit;
    }

    @SuppressWarnings("all")
    public float getValue() {
        return this._value;
    }

    @SuppressWarnings("all")
    public SVGLengthUnit getUnit() {
        return this._unit;
    }

    @Override
    @SuppressWarnings("all")
    public boolean equals(final Object o) {
        if (o == this)
            return true;
        if (!(o instanceof SVGLength))
            return false;
        final SVGLength other = (SVGLength) o;
        if (!other.canEqual((Object) this))
            return false;
        if (Float.compare(this.getValue(), other.getValue()) != 0)
            return false;
        final Object this$_unit = this.getUnit();
        final Object other$_unit = other.getUnit();
        if (this$_unit == null ? other$_unit != null : !this$_unit.equals(other$_unit))
            return false;
        return true;
    }

    @SuppressWarnings("all")
    protected boolean canEqual(final Object other) {
        return other instanceof SVGLength;
    }

    @Override
    @SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + Float.floatToIntBits(this.getValue());
        final Object $_unit = this.getUnit();
        result = result * PRIME + ($_unit == null ? 43 : $_unit.hashCode());
        return result;
    }

    @Override
    @SuppressWarnings("all")
    public String toString() {
        return "SVGLength(_value=" + this.getValue() + ", _unit=" + this.getUnit() + ")";
    }

    /**
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    public SVGLength withValue(final float _value) {
        return this._value == _value ? this : new SVGLength(_value, this._unit);
    }

    /**
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    public SVGLength withUnit(final SVGLengthUnit _unit) {
        return this._unit == _unit ? this : new SVGLength(this._value, _unit);
    }
}
