// Generated by delombok at Thu Feb 13 14:20:21 UTC 2025
package io.github.humbleui.skija.svg;

import org.jetbrains.annotations.*;

public class SVGPreserveAspectRatio {
    @ApiStatus.Internal
    public final SVGPreserveAspectRatioAlign _align;
    @ApiStatus.Internal
    public final SVGPreserveAspectRatioScale _scale;

    @ApiStatus.Internal
    public SVGPreserveAspectRatio(int align, int scale) {
        this(SVGPreserveAspectRatioAlign.valueOf(align), SVGPreserveAspectRatioScale._values[scale]);
    }

    public SVGPreserveAspectRatio() {
        this(SVGPreserveAspectRatioAlign.XMID_YMID, SVGPreserveAspectRatioScale.MEET);
    }

    public SVGPreserveAspectRatio(SVGPreserveAspectRatioAlign align) {
        this(align, SVGPreserveAspectRatioScale.MEET);
    }

    public SVGPreserveAspectRatio(SVGPreserveAspectRatioScale scale) {
        this(SVGPreserveAspectRatioAlign.XMID_YMID, scale);
    }

    @SuppressWarnings("all")
    public SVGPreserveAspectRatio(final SVGPreserveAspectRatioAlign align, final SVGPreserveAspectRatioScale scale) {
        this._align = align;
        this._scale = scale;
    }

    @SuppressWarnings("all")
    public SVGPreserveAspectRatioAlign getAlign() {
        return this._align;
    }

    @SuppressWarnings("all")
    public SVGPreserveAspectRatioScale getScale() {
        return this._scale;
    }

    @Override
    @SuppressWarnings("all")
    public boolean equals(final Object o) {
        if (o == this)
            return true;
        if (!(o instanceof SVGPreserveAspectRatio))
            return false;
        final SVGPreserveAspectRatio other = (SVGPreserveAspectRatio) o;
        if (!other.canEqual((Object) this))
            return false;
        final Object this$_align = this.getAlign();
        final Object other$_align = other.getAlign();
        if (this$_align == null ? other$_align != null : !this$_align.equals(other$_align))
            return false;
        final Object this$_scale = this.getScale();
        final Object other$_scale = other.getScale();
        if (this$_scale == null ? other$_scale != null : !this$_scale.equals(other$_scale))
            return false;
        return true;
    }

    @SuppressWarnings("all")
    protected boolean canEqual(final Object other) {
        return other instanceof SVGPreserveAspectRatio;
    }

    @Override
    @SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final Object $_align = this.getAlign();
        result = result * PRIME + ($_align == null ? 43 : $_align.hashCode());
        final Object $_scale = this.getScale();
        result = result * PRIME + ($_scale == null ? 43 : $_scale.hashCode());
        return result;
    }

    @Override
    @SuppressWarnings("all")
    public String toString() {
        return "SVGPreserveAspectRatio(_align=" + this.getAlign() + ", _scale=" + this.getScale() + ")";
    }

    /**
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    public SVGPreserveAspectRatio withAlign(final SVGPreserveAspectRatioAlign _align) {
        return this._align == _align ? this : new SVGPreserveAspectRatio(_align, this._scale);
    }

    /**
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    public SVGPreserveAspectRatio withScale(final SVGPreserveAspectRatioScale _scale) {
        return this._scale == _scale ? this : new SVGPreserveAspectRatio(this._align, _scale);
    }
}
