// Generated by delombok at Thu Feb 13 14:20:21 UTC 2025
package io.github.humbleui.skija.paragraph;

public class PlaceholderStyle {
    public final float _width;
    public final float _height;
    public final PlaceholderAlignment _alignment;
    public final BaselineMode _baselineMode;
    /**
     * <p>
     * Distance from the top edge of the rect to the baseline position. This
     * baseline will be aligned against the alphabetic baseline of the surrounding
     * text.
     * </p>
     *
     * <p>
     * Positive values drop the baseline lower (positions the rect higher) and
     * small or negative values will cause the rect to be positioned underneath
     * the line. When baseline == height, the bottom edge of the rect will rest on
     * the alphabetic baseline.
     * </p>
     */
    public final float _baseline;

    @SuppressWarnings("all")
    public PlaceholderStyle(final float width, final float height, final PlaceholderAlignment alignment,
            final BaselineMode baselineMode, final float baseline) {
        this._width = width;
        this._height = height;
        this._alignment = alignment;
        this._baselineMode = baselineMode;
        this._baseline = baseline;
    }

    @SuppressWarnings("all")
    public float getWidth() {
        return this._width;
    }

    @SuppressWarnings("all")
    public float getHeight() {
        return this._height;
    }

    @SuppressWarnings("all")
    public PlaceholderAlignment getAlignment() {
        return this._alignment;
    }

    @SuppressWarnings("all")
    public BaselineMode getBaselineMode() {
        return this._baselineMode;
    }

    /**
     * <p>
     * Distance from the top edge of the rect to the baseline position. This
     * baseline will be aligned against the alphabetic baseline of the surrounding
     * text.
     * </p>
     *
     * <p>
     * Positive values drop the baseline lower (positions the rect higher) and
     * small or negative values will cause the rect to be positioned underneath
     * the line. When baseline == height, the bottom edge of the rect will rest on
     * the alphabetic baseline.
     * </p>
     */
    @SuppressWarnings("all")
    public float getBaseline() {
        return this._baseline;
    }

    @Override
    @SuppressWarnings("all")
    public boolean equals(final Object o) {
        if (o == this)
            return true;
        if (!(o instanceof PlaceholderStyle))
            return false;
        final PlaceholderStyle other = (PlaceholderStyle) o;
        if (!other.canEqual((Object) this))
            return false;
        if (Float.compare(this.getWidth(), other.getWidth()) != 0)
            return false;
        if (Float.compare(this.getHeight(), other.getHeight()) != 0)
            return false;
        if (Float.compare(this.getBaseline(), other.getBaseline()) != 0)
            return false;
        final Object this$_alignment = this.getAlignment();
        final Object other$_alignment = other.getAlignment();
        if (this$_alignment == null ? other$_alignment != null : !this$_alignment.equals(other$_alignment))
            return false;
        final Object this$_baselineMode = this.getBaselineMode();
        final Object other$_baselineMode = other.getBaselineMode();
        if (this$_baselineMode == null ? other$_baselineMode != null : !this$_baselineMode.equals(other$_baselineMode))
            return false;
        return true;
    }

    @SuppressWarnings("all")
    protected boolean canEqual(final Object other) {
        return other instanceof PlaceholderStyle;
    }

    @Override
    @SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + Float.floatToIntBits(this.getWidth());
        result = result * PRIME + Float.floatToIntBits(this.getHeight());
        result = result * PRIME + Float.floatToIntBits(this.getBaseline());
        final Object $_alignment = this.getAlignment();
        result = result * PRIME + ($_alignment == null ? 43 : $_alignment.hashCode());
        final Object $_baselineMode = this.getBaselineMode();
        result = result * PRIME + ($_baselineMode == null ? 43 : $_baselineMode.hashCode());
        return result;
    }

    @Override
    @SuppressWarnings("all")
    public String toString() {
        return "PlaceholderStyle(_width=" + this.getWidth() + ", _height=" + this.getHeight() + ", _alignment="
                + this.getAlignment() + ", _baselineMode=" + this.getBaselineMode() + ", _baseline="
                + this.getBaseline() + ")";
    }
}
