// Generated by delombok at Thu Feb 13 14:20:21 UTC 2025
package io.github.humbleui.skija.paragraph;

public class PositionWithAffinity {
    public final int _position;
    public final Affinity _affinity;

    @SuppressWarnings("all")
    public PositionWithAffinity(final int position, final Affinity affinity) {
        this._position = position;
        this._affinity = affinity;
    }

    @SuppressWarnings("all")
    public int getPosition() {
        return this._position;
    }

    @SuppressWarnings("all")
    public Affinity getAffinity() {
        return this._affinity;
    }

    @Override
    @SuppressWarnings("all")
    public boolean equals(final Object o) {
        if (o == this)
            return true;
        if (!(o instanceof PositionWithAffinity))
            return false;
        final PositionWithAffinity other = (PositionWithAffinity) o;
        if (!other.canEqual((Object) this))
            return false;
        if (this.getPosition() != other.getPosition())
            return false;
        final Object this$_affinity = this.getAffinity();
        final Object other$_affinity = other.getAffinity();
        if (this$_affinity == null ? other$_affinity != null : !this$_affinity.equals(other$_affinity))
            return false;
        return true;
    }

    @SuppressWarnings("all")
    protected boolean canEqual(final Object other) {
        return other instanceof PositionWithAffinity;
    }

    @Override
    @SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + this.getPosition();
        final Object $_affinity = this.getAffinity();
        result = result * PRIME + ($_affinity == null ? 43 : $_affinity.hashCode());
        return result;
    }

    @Override
    @SuppressWarnings("all")
    public String toString() {
        return "PositionWithAffinity(_position=" + this.getPosition() + ", _affinity=" + this.getAffinity() + ")";
    }
}
