// Generated by delombok at Thu Feb 13 14:20:21 UTC 2025
package io.github.humbleui.skija.paragraph;

import io.github.humbleui.types.*;

public class Shadow {
    public final int _color;
    public final float _offsetX;
    public final float _offsetY;
    public final double _blurSigma;

    public Shadow(int color, Point offset, double blurSigma) {
        this(color, offset.getX(), offset.getY(), blurSigma);
    }

    public Point getOffset() {
        return new Point(_offsetX, _offsetY);
    }

    @SuppressWarnings("all")
    public Shadow(final int color, final float offsetX, final float offsetY, final double blurSigma) {
        this._color = color;
        this._offsetX = offsetX;
        this._offsetY = offsetY;
        this._blurSigma = blurSigma;
    }

    @SuppressWarnings("all")
    public int getColor() {
        return this._color;
    }

    @SuppressWarnings("all")
    public float getOffsetX() {
        return this._offsetX;
    }

    @SuppressWarnings("all")
    public float getOffsetY() {
        return this._offsetY;
    }

    @SuppressWarnings("all")
    public double getBlurSigma() {
        return this._blurSigma;
    }

    @Override
    @SuppressWarnings("all")
    public boolean equals(final Object o) {
        if (o == this)
            return true;
        if (!(o instanceof Shadow))
            return false;
        final Shadow other = (Shadow) o;
        if (!other.canEqual((Object) this))
            return false;
        if (this.getColor() != other.getColor())
            return false;
        if (Float.compare(this.getOffsetX(), other.getOffsetX()) != 0)
            return false;
        if (Float.compare(this.getOffsetY(), other.getOffsetY()) != 0)
            return false;
        if (Double.compare(this.getBlurSigma(), other.getBlurSigma()) != 0)
            return false;
        return true;
    }

    @SuppressWarnings("all")
    protected boolean canEqual(final Object other) {
        return other instanceof Shadow;
    }

    @Override
    @SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + this.getColor();
        result = result * PRIME + Float.floatToIntBits(this.getOffsetX());
        result = result * PRIME + Float.floatToIntBits(this.getOffsetY());
        final long $_blurSigma = Double.doubleToLongBits(this.getBlurSigma());
        result = result * PRIME + (int) ($_blurSigma >>> 32 ^ $_blurSigma);
        return result;
    }

    @Override
    @SuppressWarnings("all")
    public String toString() {
        return "Shadow(_color=" + this.getColor() + ", _offsetX=" + this.getOffsetX() + ", _offsetY="
                + this.getOffsetY() + ", _blurSigma=" + this.getBlurSigma() + ")";
    }

    /**
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    public Shadow withColor(final int _color) {
        return this._color == _color ? this : new Shadow(_color, this._offsetX, this._offsetY, this._blurSigma);
    }

    /**
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    public Shadow withOffsetX(final float _offsetX) {
        return this._offsetX == _offsetX ? this : new Shadow(this._color, _offsetX, this._offsetY, this._blurSigma);
    }

    /**
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    public Shadow withOffsetY(final float _offsetY) {
        return this._offsetY == _offsetY ? this : new Shadow(this._color, this._offsetX, _offsetY, this._blurSigma);
    }

    /**
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    public Shadow withBlurSigma(final double _blurSigma) {
        return this._blurSigma == _blurSigma ? this : new Shadow(this._color, this._offsetX, this._offsetY, _blurSigma);
    }
}
