// Generated by delombok at Thu Feb 13 14:20:21 UTC 2025
package io.github.humbleui.skija.paragraph;

import io.github.humbleui.types.Rect;

public class TextBox {
    public final Rect _rect;
    public final Direction _direction;

    public TextBox(float l, float t, float r, float b, int direction) {
        this(Rect.makeLTRB(l, t, r, b), Direction._values[direction]);
    }

    @SuppressWarnings("all")
    public TextBox(final Rect rect, final Direction direction) {
        this._rect = rect;
        this._direction = direction;
    }

    @SuppressWarnings("all")
    public Rect getRect() {
        return this._rect;
    }

    @SuppressWarnings("all")
    public Direction getDirection() {
        return this._direction;
    }

    @Override
    @SuppressWarnings("all")
    public boolean equals(final Object o) {
        if (o == this)
            return true;
        if (!(o instanceof TextBox))
            return false;
        final TextBox other = (TextBox) o;
        if (!other.canEqual((Object) this))
            return false;
        final Object this$_rect = this.getRect();
        final Object other$_rect = other.getRect();
        if (this$_rect == null ? other$_rect != null : !this$_rect.equals(other$_rect))
            return false;
        final Object this$_direction = this.getDirection();
        final Object other$_direction = other.getDirection();
        if (this$_direction == null ? other$_direction != null : !this$_direction.equals(other$_direction))
            return false;
        return true;
    }

    @SuppressWarnings("all")
    protected boolean canEqual(final Object other) {
        return other instanceof TextBox;
    }

    @Override
    @SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final Object $_rect = this.getRect();
        result = result * PRIME + ($_rect == null ? 43 : $_rect.hashCode());
        final Object $_direction = this.getDirection();
        result = result * PRIME + ($_direction == null ? 43 : $_direction.hashCode());
        return result;
    }

    @Override
    @SuppressWarnings("all")
    public String toString() {
        return "TextBox(_rect=" + this.getRect() + ", _direction=" + this.getDirection() + ")";
    }
}
